steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
          ["build", "-t",
          "us-central1-docker.pkg.dev/$PROJECT_ID/halalens-api/halalens-api",
          "."]

  - name: "gcr.io/cloud-builders/docker"
    args:
          ["push",
          "us-central1-docker.pkg.dev/$PROJECT_ID/halalens-api/halalens-api"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "halalens-api",
        "--image",
        "us-central1-docker.pkg.dev/$PROJECT_ID/halalens-api/halalens-api",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--port",
        "8080",
        "--allow-unauthenticated",
      ]
options:
  logging: CLOUD_LOGGING_ONLY